### ISSUE TITLE
Breaks when there are lots of available checks

### ISSUE THREAD

**Issue by bootc** [tigercomputing/nagios-mass-scheduler#3]
When there are many possible checks that can be acknowledged or scheduled, any request to schedule or acknowledge returns a server error.

This happens because the service data is stored in a session, but Flask's default implementation just keeps this in a cookie (not server side). The cookie gets so large that it is dropped by the browser, resulting in no session data.

There are two bugs: not handling a missing session gracefully and the session being abused.

This might be useful to help fix the second issue: https://pythonhosted.org/Flask-Session/

**Comment by tiger-jmw** [comment]
Still an issue:

```
mod_wsgi (pid=15026): Exception occurred processing WSGI script '/srv/mass-scheduler/wsgi.py'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb) 
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb) 
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/mass-scheduler/app.py", line 59, in index
    services = [session['services'][i] for i in service_ids]
  File "/srv/mass-scheduler/app.py", line 59, in <listcomp>
    services = [session['services'][i] for i in service_ids]
  File "/usr/lib/python3/dist-packages/werkzeug/local.py", line 368, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
KeyError: 'services'
```

**Comment by tiger-jmw** [comment]
Deployment issue (and a bug in flask)
